### ISSUE TITLE
运行时间很长,一直创建无用task

### ISSUE THREAD

**Issue by Erinable** [Clov614/microsoft-rewards-helper-action#1]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/116240736/225386315-2c74f338-a790-41f6-b72b-925330e02cdb.png">
<img width="294" alt="image" src="https://user-images.githubusercontent.com/116240736/225386813-9f5c952d-91de-4c16-9e9c-98e211e80857.png">

**Comment by Clov614** [comment]
可能是pc端ua头没加的关系，导致pc端分数一直刷取失败，已修复。还有一个潜在的原因，跨区刷分会有被暂停微软积分的风险
![KEDJIV4T67S GNBVR81RZ~G](https://user-images.githubusercontent.com/61135990/225618399-5746dabf-3cdb-40ae-a603-8798ba2bbf57.png)

**Comment by Erinable** [comment]
确实是跨区的原因

**Comment by llsliang** [comment]
一直创建无用task，
[
![image](https://user-images.githubusercontent.com/82942660/225868796-93957ad6-07e4-4f2e-b71a-469d64b2fc6d.png)
](url)
而且我是国区，这个地址为啥一直是美区呀

**Comment by Clov614** [comment]
> 一直创建无用task， [ ![image](https://user-images.githubusercontent.com/82942660/225868796-93957ad6-07e4-4f2e-b71a-469d64b2fc6d.png) ](url) 而且我是国区，这个地址为啥一直是美区呀

可能是IPS没配置好的问题
我使用的是在header头中伪装ip地址来实现跨区
[](http://ip.bczs.net/country/CN)
这是我的IPS： [14.102.128.0,2.59.154.0]

**Comment by llsliang** [comment]
我是国区和美区两个区再刷

**Comment by Clov614** [comment]
> 我是国区和美区两个区再刷，所以我该怎么做也，求助求助求助

同步一下仓库
![}137@SL3G~KC 4Z $}P7)AC](https://user-images.githubusercontent.com/61135990/225877724-f4a3b829-b943-4440-9114-51b2ff58c42d.png)

IPS可以试试这个（随便在网上找的ip，第一个是国内ip，第二个是美国ip，中间用英文逗号隔开）
[14.102.128.0,5.100.152.0]

**Comment by Clov614** [comment]
> > 
> 
> 还是不行也，还是一直重复这样 ![image](https://user-images.githubusercontent.com/82942660/225935215-3bc2e4a9-bfcc-4d78-8fe6-b5447f0d1381.png) ![image](https://user-images.githubusercontent.com/82942660/225935527-bfd46211-cafe-416a-8fec-09b3edc9e72a.png) 请问我该怎么解决捏，

会这样耶？那你手动刷会出现这个问题吗

**Comment by llsliang** [comment]
> > > 
> > 
> > 
> > 用你发的那个软件可以耍，我同时刷几个号，都是美区和国区的，有什么风险吗
> 
> 多账号貌似也有风险，不太确定，因为有些人没事有些人有事

分支这个还是刷不起
但是软件那个可以

**Comment by llsliang** [comment]
> > > 
> > 
> > 
> > 用你发的那个软件可以耍，我同时刷几个号，都是美区和国区的，有什么风险吗
> 
> 多账号貌似也有风险，不太确定，因为有些人没事有些人有事

就是建议一下只刷一个号最好吗，还是多个号只刷一个区

**Comment by Clov614** [comment]
跨区风险好像大些
分支那个跟软件的刷分策略不同

**Comment by llsliang** [comment]
> 跨区风险好像大些 分支那个跟软件的刷分策略不同

一直跨着美区和国区刷
有几天了，有两个号是国区和港区再刷

**Comment by llsliang** [comment]
> > 跨区风险好像大些 分支那个跟软件的刷分策略不同
> 
> 一直跨着美区和国区刷 有几天了，有两个号是国区和港区再刷

目前还没有封号但是有伙伴被封了

**Comment by llsliang** [comment]
> > > 跨区风险好像大些 分支那个跟软件的刷分策略不同
> > 
> > 
> > 一直跨着美区和国区刷 有几天了，有两个号是国区和港区再刷
> 
> 目前还没有封号但是有伙伴被封了

国区和港区没影响吧

**Comment by llsliang** [comment]
> > > > > 跨区风险好像大些 分支那个跟软件的刷分策略不同
> > > > 
> > > > 
> > > > 一直跨着美区和国区刷 有几天了，有两个号是国区和港区再刷
> > > 
> > > 
> > > 目前还没有封号但是有伙伴被封了
> > 
> > 
> > 国区和港区没影响吧
> 
> 不确定，因为我的号刷国区和日区貌似就被标记了，没法兑换，过几天再试试 我猜测它还是会判断你最近访问的ip，如果异常就没法兑换奖励这样子

好的，谢谢

**Comment by Clov614** [comment]
![image](https://user-images.githubusercontent.com/61135990/226084041-47afd216-e897-4771-ac97-770eeef4217b.png)
今天京东卡成功上岸

**Comment by llsliang** [comment]
> 

怎么修改请求头啊

**Comment by Clov614** [comment]
@llsliang 
[修复了某区获取积分失败导致持续创建无用task(持续刷分失败会直接跳过该区刷分)](https://github.com/Clov614/microsoft-rewards-helper-action/commit/1af5c03e5fb3305976c5387e7fe1c3e3c87150be)，请同步(Sync)本仓库，可以直接无脑将可能获取到分数的区域的IP添加入IPS。示例（中、美、日）：[14.102.128.2,2.19.128.11,2.59.154.3]
