### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by hhh2566** [Clov614/microsoft-rewards-helper-action#3]
action移动端不加积分 测试手动搜索可加 猜测移动端部分参数发生变化

**Comment by Clov614** [comment]
回宿舍抓包看看

**Comment by Clov614** [comment]
@hhh2566 刚刚修复了移动端无法获取积分这个问题，但是我发现多账号多个区获取积分极有可能某个区临时性无法获取积分(例如：刷国区、日区、美区，突然美区无法获取积分，手动也不行)导致程序陷入持续获取积分死循环，我打算加个判断，跳过

**Comment by Clov614** [comment]
@hhh2566 
多账号参考：
[工作流文件](https://github.com/clov616/microsoft-rewards-helper-action/tree/main/.github/workflows)
[Action](https://github.com/clov616/microsoft-rewards-helper-action/actions)
